// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddLANPrinter(ip: string): $CancellablePromise<void> {
    return $Call.ByID(577519913, ip);
}

export function AppVariable(): $CancellablePromise<$models.AppVariable> {
    return $Call.ByID(1369849500);
}

export function CheckLANPrinterStatus(ip: string): $CancellablePromise<boolean> {
    return $Call.ByID(2896170792, ip);
}

export function ConfirmQuit(): $CancellablePromise<boolean> {
    return $Call.ByID(2432217600);
}

export function ConfirmRemoveLANPrinter(ip: string): $CancellablePromise<boolean> {
    return $Call.ByID(3049010074, ip);
}

export function DisableAutostart(): $CancellablePromise<void> {
    return $Call.ByID(2011285980);
}

export function DownloadLogs(): $CancellablePromise<void> {
    return $Call.ByID(732817834);
}

/**
 * EmitEvent broadcasts a custom event to the frontend.
 */
export function EmitEvent(name: string, ...data: any[]): $CancellablePromise<void> {
    return $Call.ByID(2176953774, name, data);
}

export function EnableAutostart(): $CancellablePromise<void> {
    return $Call.ByID(2732499339);
}

export function GetPrinterUrl(id: string): $CancellablePromise<string> {
    return $Call.ByID(1744709682, id);
}

/**
 * GetSessionToken returns the per-launch session token that identifies HTTP
 * requests from this trusted Wails process. Called once by the frontend on
 * startup; the token is never embedded in the built JS bundle.
 */
export function GetSessionToken(): $CancellablePromise<string> {
    return $Call.ByID(182516686);
}

export function GetTroubleshootInfo(): $CancellablePromise<$models.TroubleshootInfo> {
    return $Call.ByID(736464817);
}

/**
 * GetWebViewConfig returns the public kiosk configuration (URL, enabled flag,
 * and whether a PIN has been set). The PIN itself is never returned.
 */
export function GetWebViewConfig(): $CancellablePromise<$models.WebViewConfig> {
    return $Call.ByID(1023872596);
}

export function IsAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(2419392635);
}

export function IsNetworkPrintingEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(422481465);
}

export function Printers(): $CancellablePromise<$models.Printers> {
    return $Call.ByID(802732876);
}

/**
 * ReloadKiosk broadcasts a kiosk-reload event to reload the active kiosk iframe.
 */
export function ReloadKiosk(): $CancellablePromise<void> {
    return $Call.ByID(1624634479);
}

export function SetNetworkPrintingEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2877619387, enabled);
}

/**
 * SetWebViewEnabled persists the kiosk-enabled flag.
 */
export function SetWebViewEnabled(v: boolean): $CancellablePromise<void> {
    return $Call.ByID(2126555635, v);
}

/**
 * SetWebViewPIN validates and persists the 4-digit kiosk PIN.
 */
export function SetWebViewPIN(pin: string): $CancellablePromise<void> {
    return $Call.ByID(2165969645, pin);
}

/**
 * SetWebViewURL persists the kiosk URL.
 */
export function SetWebViewURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(431585303, url);
}

/**
 * SetWindowFullscreen puts the main Wails window into or out of fullscreen
 * and hides/restores the native menu bar accordingly.
 */
export function SetWindowFullscreen(fullscreen: boolean): $CancellablePromise<void> {
    return $Call.ByID(3407438114, fullscreen);
}

/**
 * ValidateWebViewPIN returns true when pin matches the stored PIN.
 * The incoming value is compared but never logged.
 */
export function ValidateWebViewPIN(pin: string): $CancellablePromise<boolean> {
    return $Call.ByID(769478165, pin);
}
