// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppVariable {
    "serverRunning": boolean;
    "os": string;
}

export interface Printer {
    "name": string;
    "ip": string;
    "id": string;
    "isLAN": boolean;
    "lanIp"?: string;
    "online": boolean;
    "type": string;
}

export interface Printers {
    "errorMsg": string;
    "printers": Printer[] | null;
    "unavailablePrinters": UnavailablePrinter[] | null;
}

export interface TroubleshootInfo {
    "activeFirewall": string;
    "firewallZone": string;
    "port": number;
    "subnet": string;
    "localIp": string;
    "execPath": string;
}

export interface UnavailablePrinter {
    "name": string;
    "errorMsg": string;
    "isLAN": boolean;
    "lanIp"?: string;
}

/**
 * WebViewConfig is the public view of kiosk settings (PIN is never exposed).
 */
export interface WebViewConfig {
    "url": string;
    "enabled": boolean;
    "hasPIN": boolean;
}
